rabbitmq:
  host: "localhost"
  port: "5672"
  username: "{cipher}72e9f191fb78c915697f3bc1614de2fdad8d92712a4f8cba91df916c0b14a4d9"
  password: "{cipher}5dd2d099958aff9231d0656c349118caeac4bc23d52ace9c86489ed9fa8ff0cc"

ldap:
  host: "ldap.test.local"
  port: "389"
  principal: "{cipher}13633c9ce5014de41d1683fa1634a1ae818d8611dc24b0399458eb3f9ac3765b"
  password: "{cipher}0dafda1d694c477284335d5b368ce4045701206827545223fcd76c1544707ce1"

